export type ProjectTheme = {
  /** Accent color for light mode (e.g. "#5b9c00") */
  accentLight: string;
  /** Accent color for dark mode (e.g. "#a3e635") */
  accentDark: string;
  /** Accent-bg rgba for light mode */
  accentBgLight: string;
  /** Accent-bg rgba for dark mode */
  accentBgDark: string;
  /** Accent-border rgba for light mode */
  accentBorderLight: string;
  /** Accent-border rgba for dark mode */
  accentBorderDark: string;
  /** Path under /public, e.g. "/projects/skatehive/logo.svg" */
  logo: string;
  /** Optional favicon path under /public */
  favicon?: string;
};

/** One social channel a project operates, plus its posting strategy. Rendered
 *  as a subtab on the home "Socials" dashboard. */
export type SocialChannel = {
  /** Display name, e.g. "Instagram", "X", "Hive", "Farcaster" */
  platform: string;
  /** @handle for the account, if any */
  handle?: string;
  /**
   * Override the account identifier used for metrics fetching.
   * When omitted, the metrics fetcher strips the leading '@' from `handle`.
   */
  metricsAccount?: string;
  /** Public profile URL */
  url?: string;
  /** Short context line, e.g. "~7.6K followers" or "snaps in hive-173115" */
  note?: string;
  /** What this channel is for / its positioning (one or two sentences) */
  summary: string;
  /** Posting frequency, e.g. "Weekly per format" */
  cadence?: string;
  /** Voice/tone guidance */
  voice?: string;
  /** Content formats or pillars used on this channel */
  formats?: { name: string; description: string }[];
  /** Things this channel should always do */
  dos?: string[];
  /** Things this channel should never do */
  donts?: string[];
};

export type ProjectConfig = {
  /** Subdomain key, e.g. "skatehive" */
  slug: string;
  /**
   * Host label used in the URL when it DIFFERS from the slug, e.g. Reelflip's
   * portal lives at `admin.reelflip.com` → subdomain "admin" but slug "reelflip".
   * The resolver accepts BOTH the slug and this subdomain (so old + new URLs
   * work). The switcher uses this as the host label. Defaults to `slug`.
   */
  subdomain?: string;
  /** Display name, e.g. "SkateHive" */
  name: string;
  /** Used for <meta description> */
  description: string;
  /** Lowercase Hive usernames allowed to access this portal */
  allowlist: string[];
  /** CSS-var overrides for accent family + asset paths */
  theme: ProjectTheme;
  hive: {
    /** Hive account that posts content (maps to HIVE_POSTING_ACCOUNT env) */
    account: string;
    /** Community tag, e.g. "hive-173115" */
    community: string;
    /** Hive web frontend base URL for this project, e.g. "https://skatehive.app".
     *  When absent, universal frontends (peakd.com) are used instead. */
    frontend?: string;
  };
  farcaster: {
    /** Farcaster channel ID, e.g. "skateboard" */
    channel: string;
    /** Optional: env key suffix for the signer UUID (reads ${prefix}_NEYNAR_SIGNER_UUID) */
    signerEnvKey?: string;
  };
  /** Default GitHub repos for Repo-to-Social, formatted as "owner/name" */
  repos: string[];
  /**
   * Social channels this project operates, with the posting strategy for each.
   * Rendered as subtabs on the home "Socials" dashboard. Each project shows
   * only its own channels (Reelflip = Instagram only).
   */
  socials: SocialChannel[];
  /**
   * Optional weekly-recap spec. When set, the campaign "Weekly Recap" template
   * is generated by THIS project's agent from its own live sources/tools/memory
   * (not a fixed Hive-posts injection), covering `sections` in the agent's own
   * voice. When absent, the project falls back to the SkateHive Hive-posts flow.
   */
  weeklyRecap?: {
    /** The signals/sections the agent should compile, in its own words. */
    sections: string[];
    /** Hint about which of the agent's own tools/sources to pull from. */
    sourcesHint?: string;
  };
  /**
   * Route paths to hide from the sidebar AND block (404) for this project,
   * e.g. ["/userbase", "/repo-to-social"]. Omitted/empty = all routes enabled.
   */
  hiddenRoutes?: string[];
  /**
   * When true, the Post Creator nav item and /post-creator route are enabled
   * for this project. Reelflip only for now.
   */
  postCreator?: boolean;
  /**
   * Overrides for campaign-artifact generation (brief + cross-platform drafts).
   * When absent, the default "growth lead at a community-owned Hive platform"
   * framing is used (SkateHive/Gnars). Set this for brands where that's wrong
   * (e.g. Reelflip — an Instagram-first editorial brand).
   */
  campaignArtifacts?: {
    /** Replaces "the growth lead at {name} — a community-owned platform built on Hive". */
    persona?: string;
    /** Extra voice/tone guidance injected into the artifact prompts. */
    voiceHint?: string;
  };
  /**
   * Google Analytics 4 and Search Console configuration.
   * When absent, the Analytics nav item is hidden and /analytics returns 404.
   */
  analytics?: {
    /** GA4 property ID, e.g. "527345741" */
    ga4PropertyId?: string;
    /** GSC site URL, e.g. "sc-domain:skatehive.app" */
    gscSiteUrl?: string;
    /**
     * ISO 3166-1 alpha-2 country codes to EXCLUDE from GA4 reports (treated as
     * bot traffic), e.g. ["SG"]. Applied as a countryId dimensionFilter to
     * every GA4 report.
     */
    excludeCountries?: string[];
    /**
     * Queries containing these terms (case-insensitive substring) are "branded".
     * Used in the GSC branded vs non-branded split. Defaults to [project.name.toLowerCase()].
     */
    brandedTerms?: string[];
  };
  /**
   * Agents whose morning briefings render on this project's home page (one tab
   * each). Each maps to an OpenClaw agent slug + its workspace dir.
   */
  briefingAgents: {
    slug: string;
    label: string;
    /** Short label for the tab strip; defaults to `label`. */
    tabLabel?: string;
    workspace: string;
  }[];
  agent: {
    /**
     * Uppercase prefix for namespaced env vars.
     * e.g. "SKATEHIVE" reads SKATEHIVE_GATEWAY_URL, SKATEHIVE_GATEWAY_TOKEN, etc.
     */
    gatewayEnvPrefix: string;
    /** OpenClaw agentId, e.g. "skatehive-marketing" */
    id: string;
    /** Display name shown in the chat header, e.g. "SkateHive Marketing" */
    displayName: string;
    /** Optional emoji prefix for the agent */
    emoji?: string;
    /** First assistant message shown in the chat before any user interaction */
    greeting?: string;
  };
  prompts?: {
    /** Directory (relative to project root) where prompt overrides live */
    dir: string;
  };
  /**
   * Email addresses of the project's core team. Used for the Morning Brief
   * "Email to team" action — sends the briefing by BCC to all addresses.
   * Omitting this (or leaving it empty) will disable the send action.
   */
  teamEmails?: string[];
  /**
   * GitHub Projects V2 configuration. When set, the Kanban nav item is shown
   * and /kanban renders the board for this project. Gated like `analytics` —
   * absent = nav hidden + /kanban returns 404.
   */
  githubProject?: {
    /** GitHub org login that owns the project, e.g. "SkateHive" */
    org: string;
    /** GitHub Project number (Projects V2), e.g. 1 */
    number: number;
  };
};
